spring:
    application:
        name: demo

    datasource:
        url: jdbc:postgresql://localhost:5432/bootcamp
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                format_sql: true
                default_schema: public

    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yaml

aws:
    s3:
        region: us-east-1
        bucket: cars-photos
        endpoint: http://localhost:4566
        access-key: test
        secret-key: test
app:
    jwt:
        secret: minha-chave-super-secreta-com-mais-de-32-caracteres
        expirations-ms: 3600000